### ISSUE TITLE
Update DB seed data 'createdDate' value to be time.Time compatable or convert it while inserted into DB

### ISSUE THREAD

**Issue by sbeckstrand** [Brich96/usu-gdsf#37]
With the current setup, it is not possible to get game objects from the DB due to not being able to convert the createdDate string values for the seed data to a time.Time type.

**Comment by kp-121** [comment]
I think we should keep it as a string, then convert it to a Time object when we need to. It is much easier to handle as a string, especially with the database.

**Comment by hagen-larsen-hl** [comment]
I'm thinking its best to have a time stamp for creation rather than just a date. We'll probably need to update the seed data anyways, shouldn't it be pretty easy to access time.Time types from the database if we know to anticipate it when serializing/deserializing?

**Comment by kp-121** [comment]
#38 Sounds good, I'll just convert it at the database level.

**Comment by hagen-larsen-hl** [comment]
I'll go ahead and take care of it, I'd like to contribute some more code to the code base
