### ISSUE TITLE
Update backend game model to match frontend

### ISSUE THREAD

**Issue by hagen-larsen-hl** [Brich96/usu-gdsf#43]
Game model needs attributes:

![image](https://user-images.githubusercontent.com/95707878/182265837-c6bb1d19-e270-430b-aa7f-eb4e8e410643.png)

**Comment by hagen-larsen-hl** [comment]
It looks like we have some name clashing with "developer" in the front-end and "Author" in the backend, have we discussed which we would like to keep? Probably best to keep naming consistent. Also, do we need to store an image path in the database? Seems like we would probably store the actual image instead. @Brich96 @kp-121

**Comment by kp-121** [comment]
As long as it stays a string, I don't think changing the variable name matters much. It's up to @Brich96 though

**Comment by Brich96** [comment]
lets make it developer instead of author for consistency, probably not that big of a deal but that way we use the same descriptor.
